import { exportName, moduleName } from "./naming.ts";
import type { SpecOperation } from "./operations.ts";

export const generatedHeader =
  "// Generated by `npm run generate` from openapi/openapi.yaml. Do not edit by hand.";

/**
 * Turns a spec `description` into JSDoc-safe prose.
 *
 * SevDesk's descriptions are HTML fragments with hard line breaks and links, so they need
 * flattening before they can sit in a comment.
 */
export const toDocText = (text: string): string =>
  text
    .replaceAll(/<br\s*\/?>/giu, " ")
    .replaceAll(/<[^>]+>/gu, "")
    .replaceAll("&nbsp;", " ")
    .replaceAll(/\s+/gu, " ")
    // A literal `*/` would end the comment early.
    .replaceAll("*/", "*⁄")
    .trim();

const toJsDoc = (operation: SpecOperation): string => {
  const lines: Array<string> = [];
  const summary = operation.summary === undefined ? "" : toDocText(operation.summary);
  const description = operation.description === undefined ? "" : toDocText(operation.description);

  if (summary !== "") {
    lines.push(summary);
  }

  if (description !== "" && description !== summary) {
    if (lines.length > 0) {
      lines.push("");
    }

    lines.push(description);
  }

  lines.push("", `\`${operation.method} ${operation.path}\``);

  if (operation.paginated) {
    lines.push("", "Paginated — use `.pages()` to walk every page.");
  }

  if (operation.deprecated) {
    lines.push("", "@deprecated Marked as deprecated in the sevDesk API spec.");
  }

  return ["/**", ...lines.map((line) => (line === "" ? " *" : ` * ${line}`)), " */"].join("\n");
};

const toOperationSource = (operation: SpecOperation): string => {
  const id = JSON.stringify(operation.operationId);
  // The type is written out rather than inferred: JSR rejects "slow types" —
  // public symbols whose type it cannot read off the source — and an explicit
  // annotation also makes editor hover show the operation instead of a
  // conditional type.
  const type = `${operation.paginated ? "PaginatedOperation" : "Operation"}<${id}>`;

  return [
    toJsDoc(operation),
    `export const ${exportName(operation.operationId)}: ${type} = defineOperation(`,
    `  ${id},`,
    `  {`,
    `    method: ${JSON.stringify(operation.method)},`,
    `    path: ${JSON.stringify(operation.path)},`,
    ...(operation.paginated ? ["    paginated: true,"] : []),
    `  },`,
    `);`,
  ].join("\n");
};

/** Groups operations by tag, preserving spec order within each group. */
export const groupByModule = (
  operations: Array<SpecOperation>,
): Map<string, Array<SpecOperation>> => {
  const modules = new Map<string, Array<SpecOperation>>();

  for (const operation of operations) {
    const name = moduleName(operation.tag);

    modules.set(name, [...(modules.get(name) ?? []), operation]);
  }

  return modules;
};

/** Renders one tag module, e.g. `src/generated/contact.ts`. */
export const emitModule = (tag: string, operations: Array<SpecOperation>): string =>
  [
    generatedHeader,
    "",
    `/**`,
    ` * sevDesk \`${tag}\` endpoints.`,
    ` *`,
    ` * @module`,
    ` */`,
    "",
    `import {`,
    `  defineOperation,`,
    ...(operations.some(({ paginated }) => paginated) ? [`  type PaginatedOperation,`] : []),
    ...(operations.some(({ paginated }) => !paginated) ? [`  type Operation,`] : []),
    `} from "../core/operation.ts";`,
    "",
    operations.map((operation) => toOperationSource(operation)).join("\n\n"),
    "",
  ].join("\n");

/**
 * The `exports` map, shared by package.json (pointing at built `dist/`) and jsr.json (pointing at
 * `src/`, since JSR publishes source).
 *
 * Neither registry supports wildcards for what we need here, so every subpath is listed — which is
 * exactly why this is generated rather than hand-written.
 */
export const emitExports = (
  moduleNames: Array<string>,
  { jsr }: { jsr: boolean },
): Record<string, string> => {
  const toPath = (name: string) => (jsr ? `./src/${name}.ts` : `./dist/${name}.js`);

  return {
    ".": toPath("main"),
    "./types": toPath("generated/api"),
    ...Object.fromEntries(
      moduleNames
        .toSorted((a, b) => a.localeCompare(b))
        .map((name) => [`./${name}`, toPath(`generated/${name}`)]),
    ),
  };
};
