export { createClient, defaultBaseUrl } from "./core/client.ts";
export type { Client, ClientConfig } from "./core/client.ts";

export {
  BadRequest,
  Conflict,
  Forbidden,
  httpErrorForStatus,
  InvalidResponse,
  NetworkError,
  NotFound,
  RateLimited,
  ServerError,
  SevDeskError,
  SevDeskHttpError,
  Unauthorized,
  UnexpectedStatus,
} from "./core/errors.ts";
export type { RequestContext, ResponseContext, SevDeskErrorPayload } from "./core/errors.ts";

export {
  buildPath,
  buildSearchParams,
  defineOperation,
  defineUndocumentedCollection,
  defineUndocumentedOperation,
} from "./core/operation.ts";
export type {
  Args,
  BodyOf,
  HttpMethod,
  Operation,
  OperationConfig,
  OperationId,
  PaginatedOperation,
  PaginationParams,
  PathOf,
  QueryOf,
  QueryValue,
  ResponseOf,
  UndocumentedArgs,
  UndocumentedCollection,
  UndocumentedOperation,
  UndocumentedPaginatedOperation,
} from "./core/operation.ts";

export { defaultPageSize, paginate } from "./core/pagination.ts";

/**
 * Every type the sevDesk OpenAPI spec defines — request bodies, response models, parameters — as
 * generated by `openapi-typescript`.
 *
 * ```ts
 * import type { components } from "@peerigon/sevdesk/types";
 *
 * type Contact = components["schemas"]["Model_ContactResponse"];
 * ```
 */
export type { components, operations, paths } from "./generated/api.ts";
